apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  annotations:
    konghq.com/gateway-unmanaged: kong/kong-kong-proxy
  name: kong
spec:
  gatewayClassName: gateway-class
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
  - name: proxy-ssl
    port: 443
    protocol: HTTPS
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway-api
  hostnames:
  - "mvitormais.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /greet/hi
    backendRefs:
    - name: hi-hostname-api-service
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /greet/hello
      method: GET
    backendRefs:
    - name: hello-hostname-api-service
      port: 8080