apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: greetingapi-lb
spec:
  controllerName: greetingapi.io/gateway-controller
  parametersRef:
    name: greetingapi-lb
    group: greetingapi.io
    kind: Parameters
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: my-gateway-api
spec:
  gatewayClassName: greetingapi-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway-api
  hostnames:
  - "mvitor.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /greet/hi
    backendRefs:
    - name: hi-hostname-api
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /greet/hello
      method: GET
    backendRefs:
    - name: hello-hostname-api
      port: 8080